[package]
name = "static-web-server"
version = "2.8.0"
authors = ["Jose Quintana <https://joseluisq.net>"]
license = "MIT OR Apache-2.0"
description = "A blazing fast and asynchronous web server for static files-serving."
repository = "https://github.com/joseluisq/static-web-server"
readme = "README.md"
keywords = [
    "static-web-server",
    "file-server",
    "http-server",
    "docker-image",
    "musl-libc",
    "x86",
    "x86-64",
    "arm64",
    "linux",
    "darwin",
    "windows",
]
categories = ["network-programming", "web-programming::http-server"]
edition = "2021"
include = ["src/**/*", "Cargo.toml", "Cargo.lock"]

[[bin]]
name = "static-web-server"
path = "src/bin/server.rs"

[features]
default = [ ]
tls = [ "tokio-rustls" ]
http2 = [ "tls" ]

[dependencies]
anyhow = "1.0"
async-compression = { version = "0.3", default-features = false, features = ["brotli", "deflate", "gzip", "tokio"] }
bcrypt = "0.10"
bytes = "1.1"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
headers = { git = "https://github.com/joseluisq/hyper-headers.git", branch = "headers_encoding" }
http = "0.2"
humansize = "1.1"
hyper = { version = "0.14", features = ["stream", "http1", "http2", "tcp", "server"] }
listenfd = "0.5"
mime_guess = "2.0"
num_cpus = { version = "1.13" }
percent-encoding = "2.1"
pin-project = "1.0"
structopt = { version = "0.3", default-features = false }
time = { version = "0.1", default-features = false }
tokio = { git = "https://github.com/john-sharratt/tokio.git", branch = "wasix-1.21.2", default-features = false, features = ["rt-multi-thread", "macros", "fs", "io-util", "signal"] }
#tokio = { path = "../tokio/tokio", default-features = false, features = ["rt-multi-thread", "macros", "fs", "io-util", "signal"]  }
tokio-rustls = { version = "0.23", optional = true }
rustls-pemfile = "0.2"
tokio-util = { version = "0.7", default-features = false, features = ["io"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["smallvec", "parking_lot", "fmt", "ansi", "tracing-log"] }
form_urlencoded = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_ignored = "0.1"
toml = "0.5"
http-serde = "1.1"
globset = { version = "0.4", features = ["serde1"] }

[patch.crates-io]
socket2 = { git = "https://github.com/john-sharratt/socket2.git", branch = "wasix" }
libc = { git = "https://github.com/john-sharratt/libc.git" }
tokio = { git = "https://github.com/john-sharratt/tokio.git", branch = "wasix-1.21.2" }
#tokio = { path = "../tokio/tokio" }
mio = { git = "https://github.com/john-sharratt/mio.git", branch = "wasix" }
#mio = { path = "../mio" }
#ring = { git = "https://github.com/john-sharratt/ring.git", branch = "v0.16.20" }
#ring = { path = "../ring" }

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.tikv-jemallocator]
version = "0.4"

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.3", features = ["extended-siginfo"] }
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"], default-features = false }

[target.'cfg(windows)'.dependencies]
windows-service = { git = "https://github.com/joseluisq/windows-service-rs" }
windows-sys = { version = "0.36.1", features = [ "Win32_Foundation", "Win32_NetworkManagement_IpHelper", "Win32_Networking_WinSock", "Win32_System_Memory" ] }

[dev-dependencies]
bytes = "1.1"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = "fat"
opt-level = 3
panic = "abort"
rpath = false
